title: Hello, world! I'm Martin Nilsson
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Martin Nilsson # add your name
author-img: david-freeman.jpg # add your photo
about-author: I am sys-admin and architect focusing on infracstructure and more recently Infrastructure as Code. Always hungry to keep learning. # add description
social-twitter: mytsse # add your Twitter handle
social-facebook: n/a # add your Facebook handle
social-github: artemsheludko # add your Github handle
social-linkedin: martin-sysadmin  # add your Linkedin handle
social-email: n/a # add your Email address

# Disqus
discus-identifier: n/a # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
